server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://host.minikube.internal:5431/postgres
    username: postgres
    password: postgres
  rabbitmq:
    host: host.minikube.internal
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

queue:
  name: transactions