spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
#  rabbitmq:
#    host: host.minikube.internal
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate